name: build python

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python_version: ['3.8', '3.9', '3.10']
        os: [ ubuntu-latest, macos-latest ]
    steps:
    - name: checkout pyoxidizer
      uses: actions/checkout@master
      with:
        repository: indygreg/PyOxidizer
        ref: main

    - name: build python
      run: |
        set -x
        mkdir -p build
        cargo install --path ./pyoxidizer
        cd pyoxy
        pyoxidizer build --var PYTHON_VERSION ${{ matrix.python_version }} --release
        CFG="$(find $(pwd) -name pyo3-build-config-file.txt)"
        PYO3_CONFIG_FILE="$CFG" cargo build --release
        PY="$(sed -rn 's/^executable=(.*)$/\1/p' $CFG)"
        mv "$(dirname $(dirname $PY))" ../build
    - name: inspect
      run: |
        ./build/install/bin/python3 -m sysconfig
    - name: build wheel
      run: |
        mkdir -p wheel/interpreter-${{ matrix.python_version }}.data/data/
        mv build/install/bin/python3 wheel/interpreter-${{ matrix.python_version }}.data/data/python
        wheel_name="interpreter-${{ matrix.python_version }}-py2.py3-none-$(python -c "import sysconfig;print(sysconfig.get_platform().replace('.', '_').replace('-', '_'))").whl"
        zip $wheel_name wheel/
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        path: "*.whl"
