name: bzip2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout bzip2
      uses: actions/checkout@master
      with:
        repository: libarchive/bzip2
        ref: refs/tags/bzip2-1.0.8
    - name: make
      run: make
