name: bzip2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        name: libarchive/bzip2
        ref: refs/heads/bzip2-1.0.8
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
