name: cpython

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout cpython
      uses: actions/checkout@master
      with:
        repository: python/cpython
        ref: refs/tags/v3.10.4
    - name: configure
      run: ./configure
    - name: make
      run: make
# full test suite will take hours
#    - name: test
#      run: make test
