name: cpython

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
    - name: checkout cpython
      uses: actions/checkout@master
      with:
        repository: python/cpython
        ref: refs/tags/v3.10.4
    - name: configure
      run: ./configure LDFLAGS='-static' --disable-shared  --enable-optimizations
    - name: enable static modules
      run: echo '*static*' > Modules/Setup.local && sed -n -E 's/^#([a-z_].*)$/\1/p' Modules/Setup >> Modules/Setup.local && sed -i.bak '/^_\{0,1\}xx/d' Modules/Setup.local && sed -i.bak '/^_test/d' Modules/Setup.local
    - name: make
      run: make LDFLAGS='-static' LINKFORSHARED=' '
    - name: test
      run: ./python  -V
# full test suite will take hours
#      run: make test
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: python
        path: python.exe
