name: pyo

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
    - name: checkout pyoxidizer
      uses: actions/checkout@master
      with:
        repository: indygreg/PyOxidizer
        ref: main
    - name: build
      run: |
        set -x
        mkdir -p build
        cargo install --path ./pyoxidizer
        cd pyoxy
        pyoxidizer build --var PYTHON_VERSION 3.8 --release
        CFG=$(find $(pwd) -name pyo3-build-config-file.txt)
        PYO3_CONFIG_FILE=$CFG cargo build --release
        PY=$(grep -Po '(?<=executable=).*' $CFG)
        mv $(dirname $(dirname $PY)) ../build
        ls -ld ../build
        ls -l ../build
        ls -l ../build/install
    - name: inspect
      run: |
        ./build/install/bin/python3 -m sysconfig
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: python
        path: build/install
